### ISSUE TITLE
Popup shows: ⚠️ undefined

### ISSUE THREAD

**Issue by Juraj-Masiar** [ProtonVPN/proton-vpn-browser-extension#2]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------

Hello, I'm here to report a small usability bug:
STR:
1. install Proton VPN to Firefox ESR 115
2. open popup
3. see the "⚠️ undefined", not very professional looking :)
![image](https://github.com/user-attachments/assets/0555c0f1-6556-49e0-bcdd-0609f71abd6a)

Trivial fix that will make the first impression much better!

**Comment by kylekatarnls** [comment]
Thanks for report, we have this also in our fix list, and this should get fixed in the next version.

**Comment by kylekatarnls** [comment]
This should now be fixed in 1.2.3

**Comment by DigitalForceEU** [comment]
still doesn't work after an update. Seems like only the error changed.

Waterfox (G6.0.20 64 bit) on ubuntu 24.04

![image](https://github.com/user-attachments/assets/f9716bba-d33b-43cf-8a6a-131c18699805)
![image](https://github.com/user-attachments/assets/a62a23d6-4d4b-49b4-a5a3-91ac9f95398e)

**Comment by ptkovsky** [comment]
Still same behavior on Windows 7 using Firefox ESR 115.17.0.

An extension fix would be really helpful, since dedicated ProtonVPN app feels way too resource heavy, especially when running on limited VMs or legacy hardware.
